branch-defaults:
  developer:
    environment: get-started-express-dev
  master:
    environment: get-started-express-prod
global:
  application_name: get-started-express
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.14.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
