version: 2.1

executors:
  base-eb:
    docker:
      - image: davidwfs/base-eb:latest
    working_directory: ~/app

jobs:
  credential:
    executor: base-eb
    steps:
      - run:
          name: AWS credentials file
          working_directory: /
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config

      - persist_to_workspace:
          root: ~/.aws
          paths:
            - config

  deploy_to_prod:
    executor: base-eb
    steps:
      - checkout
      - attach_workspace:
          at: ~/.aws
      - run:
          name: Deploying
          command: eb deploy get-started-express-prod

  deploy_to_dev:
    executor: base-eb
    steps:
      - checkout
      - attach_workspace:
          at: ~/.aws
      - run:
          name: Deploying
          command: eb deploy get-started-express-dev

workflows:
  version: 2
  deploy:
    jobs:
      - credential:
          filters:
            branches:
              only:
                - master
                - developer
      - deploy_to_prod:
          requires:
            - credential
          filters:
            branches:
              only:
                - master
      - deploy_to_dev:
          requires:
            - credential
          filters:
            branches:
              only:
                - developer
