version: 2.1

executors:
  node-executor:
    docker:
      - image: davidwfs/base-eb:latest
    working_directory: ~/app

jobs:
  credential:
    executor: node-executor
    steps:
      - run:
          name: Creating AWS credentials file
          working_directory: /
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config

      - persist_to_workspace:
          root: ~/.aws
          paths:
            - config

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/.aws
      - run:
          name: Deploying
          command: eb deploy

workflows:
  version: 2
  build:
    jobs:
      - credential
      - deploy:
          requires:
            - credential
          filters:
            branches:
              only:
                - master
